### ISSUE TITLE
OpenGL Context Creation fails sometimes

### ISSUE THREAD

**Issue by WeirdConstructor** [WeirdConstructor/Kickmess#4]
Reported by "Reiso van den Berg":

```
if this helps, i've tried running kickmess in both ardour and carla, both crashed
also pop os
also nvidia drivers
with ardour it gives me these lines 

Reading kickmess took 3 microseconds, final size = 0
Do *not* Emulate VST Bypass Port for Kickmess (VST)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: CreationFailed', src/window.rs:387:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /home/weictr/.cargo/git/checkouts/baseview-0a7ca4e4ca707ee8/3cb9848/src/x11/window.rs:61:27
fatal runtime error: failed to initiate panic, error 5
fish: “Ardour6” terminated by signal SIGABRT (Abort)
```

**Comment by WeirdConstructor** [comment]
I'll need to revisit the GlContext creation in window.rs at some point.
